#!/usr/bin/env python
import sys
import socket
import time
from ctypes import cdll

lib = cdll.LoadLibrary('./libControl.so')

class Command:
	def create_from(self,argarray):
		return
	def execute(self):
		return
	def toCommands(self):
		return ''

{% for command in commands %}
class {{command.prefix}}_Command(Command):
        def create_from(self, argarray ):
                {% for i in range( command.numargs ) %}
                self.v{{i}} = argarray[{{i}}]
                {% endfor %}
		return

        def execute(self):
                {% for funct in command.functions %}
                lib.lib_{{funct | re_sub("v[0-9]","self.\g<0>")}}
                {% endfor %}
		return

        def toCommands(self):
                out = ""
		{% for funct in command.functions %}
		out+="{{funct | re_sub("v[0-9]","\"+str(self.\g<0>)+\"")}};\n"
		{% endfor %}
		return out
{% endfor %}


commandSet = dict(
{% for command in commands %}
 {{command.prefix}}={{command.prefix}}_Command {% if not loop.last%},{% endif %}
{% endfor %}
)
